### ISSUE TITLE
Failed to start ZAP process through zap-pipeline

### ISSUE THREAD

**Issue by preddy-hub** [jenkinsci/zap-pipeline-plugin#15]
Hi,
When I am trying to execute the jenkins job with zap pipeline and I am seeing below issue "java.lang.Throwable: zap: Failed to start ZAP process". Please let me know how I can solve this. I am running this on windows.

pipeline {
    agent any
    stages { 
        stage('Setup') {
            steps {
                script {
                    startZap(host: "localhost", port: 8080, timeout:500, zapHome: "C/ZAPXXXX..", sessionPath:"XXXX", allowedHosts:['localhost'])
                }
            }
        }
        stage('Build & Test') {
            steps {
                script {
                    sh "mvn verify -Dhttp.proxyHost=localhost -Dhttp.proxyPort=8080 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8080" // Proxy tests through ZAP
                }
            }
        }
    }
    post {
        always {
            script {
                archiveZap(failAllAlerts: 1, failHighAlerts: 0, failMediumAlerts: 0, failLowAlerts: 0, falsePositivesFilePath: "zapFalsePositives.json")
            }
        }

ERROR LOG:
[Pipeline] End of Pipeline
java.lang.Throwable: zap: Failed to start ZAP process
	at com.vrondakis.zap.workflow.StartZapExecution.start(StartZapExecution.java:68)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor414.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
    }
}

**Comment by shardy-lbar** [comment]
Hi,

Sorry for the very late reply. This error message occurs when the plugin could not start the ZAP application. Please ensure that your provided zapHome path is correct.

**Comment by shardy-lbar** [comment]
The most recent version (1.12) includes improvemens to the error logging, so that the original causes of errors such as your's will be printed. Can you please upgrade, and if the issue is still occurring, supply the new stack trace.
Thanks
